- name: Configure K3s
  hosts: localhost
  become: false
  gather_facts: false

  pre_tasks:
    - name: Import Plugin Map
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/plugin_map.yaml"
        name: plugin_map

    - name: Dump Plugin Map
      ansible.builtin.debug:
        var: plugin_map
        verbosity: 2

    - name: Fetch cluster config files
      ansible.builtin.include_role:
        name: get_cluster_config
      when: (config_repo is defined) or (config_dir is defined)

  roles:
    - apply_config
