---
- name: Dump cluster_config
  ansible.builtin.debug:
    var: cluster_config
    verbosity: 2

- name: Dump plugin_map
  ansible.builtin.debug:
    var: plugin_map
    verbosity: 2

- name: Test filter
  ansible.builtin.debug:
    msg: "{{ cluster_config | get_disables(plugin_map) }}"
    verbosity: 2

- name: Get installer
  ansible.builtin.get_url:
    url: "{{ k3s_url }}"
    dest: "{{ install_script }}"
    mode: '0755'

- name: Install K3s Master Node
  ansible.builtin.command:
    cmd: "{{ install_script }} {{ cluster_config | get_disables(plugin_map) }}"
    creates: /var/lib/rancher/k3s/server/node-token
