---
- name: Purge work dir
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: absent
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false

- name: Create work dir
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    mode: '0700'
  run_once: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false

- name: Fetch files
  ansible.builtin.fetch:
    src: "{{ config_file.path }}/{{ config_file.file }}"
    dest: "{{ work_dir }}/{{config_file.file}}"
    mode: "0600"
    flat: true
  run_once: true
  changed_when: false
  with_items: "{{ config_files }}"
  loop_control:
    loop_var: config_file
