---
- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    groups:
      - sudo
  when: manage_service_account | default(true)

- name: Set a fact for the ssh_key file path
  ansible.builtin.set_fact:
    prep_hosts_path: "~/.ssh/{{ id_ed25519.pub | default('id_ed25519.pub') }}"

- name: Add authorized keys
  ansible.builtin.authorized_key:
    user: ansible
    key: "{{ lookup('file', prep_hosts_path) }}"

- name: Make ansible sudo password-less
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^%ansible"
    line: "%ansible ALL=(ALL) NOPASSWD: ALL"
  when: service_account_nopasswd | default(true)

- name: Configure Hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update all packages to their latest version
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: patch_everything | default(false)

- name: Install Things
  ansible.builtin.apt:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ prep_hosts_pkgs_ubuntu }}"
  loop_control:
    loop_var: pkg

- name: Set a fact for if prometheus is selected for install
  ansible.builtin.set_fact:
    manage_prometheus: '"prometheus" in cluster_config | get_enabled_plugins(plugin_map)'
  when: cluster_config is defined

- name: Remove apt installed Prometheus package
  ansible.builtin.apt:
    name: "{{ prep_hosts_prom_pkg }}"
    state: absent
  when: manage_prometheus | default(false)

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: true
