---
- name: Clone repo without creds
  ansible.builtin.git:
    repo: "{{ config_repo }}"
    dest: "{{ playbook_dir }}/config"
    force: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
  when: GIT_USER is not defined

- name: Clone repo via pw
  ansible.builtin.git:
    repo: https://{{ GIT_USER | urlencode }}:{{ GIT_PWD | urlencode }}@{{ config_repo }}
    dest: "{{ playbook_dir }}/config"
    force: true
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
  when: GIT_USER is defined