---
- name: Fetch config from git
  ansible.builtin.include_tasks:
    file: git.yaml
  when: config_repo is defined 

- name: Copy Local dir to ./config
  ansible.builtin.include_tasks:
    file: directory.yml
  when: config_dir is defined

- name: Load config
  ansible.builtin.include_vars: 
    file: "{{ playbook_dir }}/config/cluster-config.yaml"
    name: cluster_config
  delegate_to: 127.0.0.1
  changed_when: false
  become: false
